project:
  description: Amazon::Lambda::Runtime
  author:
    name: Rob Lauer
    mailto: rlauer@treasurersbriefcase.com
pm_module: Amazon::Lambda::Runtime
min-perl-version: 5.010
dependencies:
  requires: requires
  test_requires: test-requires
path:
  pm_module: lib
  exe_files: bin
  tests: t
extra-files:
  - ChangeLog
  - share:
      - README.md
      - Makefile.build
      - LambdaHandler.pm.in
      - Dockerfile
      - policies
      - cpanfile
      - cpanfile.snapshot
      - sqs-test.mk
      - s3-test.mk
      - sns-test.mk
      - streaming-test.mk
      - eventbridge-test.mk
      - payload-sns.json
      - payload.json
      - version.mk
      - ecr-create-repo.mk
resources:
  homepage: http://github.com/rlauer6/Amazon-Lambda-Runtime2.git
  bugtracker:
    web: http://github.com/rlauer6/Amazon-Lambda-Runtime2/issues
    mailto: rlauer@treasurersbriefcase.com
  repository:
    url: git://github.com/rlauer6/Amazon-Lambda-Runtime2.git
    web: http://github.com/rlauer6/Amazon-Lambda-Runtime2.git
    type: 'git'
